APP_NAME: "customer-rest-service"
APP_HTTP_PORT: "4002"

DB_DSN: "root:password@tcp(localhost:3306)/customer?parseTime=true"
DB_MAX_IDLE_CONNECTIONS: "20"
DB_MAX_OPEN_CONNECTIONS: "100"
DB_MAX_IDLE_DURATION_IN_SECS: "60"
DB_MAX_LIFE_TIME_DURATION_IN_SECS: "300"

KAFKA_BROKERS: "localhost:9092"